create table tb_category (id int8 generated by default as identity, created_at TIMESTAMP WITHOUT TIME ZONE, name varchar(255), updatedd_at TIMESTAMP WITHOUT TIME ZONE, primary key (id));
create table tb_product (id int8 generated by default as identity, date TIMESTAMP WITHOUT TIME ZONE, description TEXT, img_url varchar(255), name varchar(255), price float8, primary key (id));
create table tb_product_category (product_id int8 not null, category_id int8 not null, primary key (product_id, category_id));
alter table if exists tb_product_category add constraint FK5r4sbavb4nkd9xpl0f095qs2a foreign key (category_id) references tb_category;
alter table if exists tb_product_category add constraint FKgbof0jclmaf8wn2alsoexxq3u foreign key (product_id) references tb_product;
